### ISSUE TITLE
Songs do not play

### ISSUE THREAD

**Issue by thekaigonzalez** [Cliometric/NFY#3]
Also, time does not show up properly before pause.

**Comment by thekaigonzalez** [comment]
Correction: Song specifically doesn't play after installation using 0.0.2 setup, maybe it's a cache error.

**Comment by threecerny** [comment]
it's trying to get it from app.asar

**Comment by threecerny** [comment]
it's going to be fixed soon

**Comment by thekaigonzalez** [comment]
> 

Yeah, because when I loaded from my custom build, it worked fine
when I use the setup (for the latest), it doesn't work!

Maybe it's because the setup is not up to date, will this be a 0.0.3 patch or is it already fixed?
